### PR TITLE
CRIMAP-600 Add first court hearing details to CYA

### PR DESCRIPTION
**Pull request by zheileman**
## Description of change
Follow-up to previous PRs #493 and #494 to add the first court hearing details (if any) to the check your answers page.

Also bump to the schemas version where this new attributes are part of the Struct to be able to read back submitted applications.

If the first court hearing question was not asked, we hide the row and section.

It is important to merge this datastore PR too otherwise when reading submitted applications will not have the new attributes: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/175

## Link to relevant ticket
https://dsdmoj.atlassian.net/browse/CRIMAP-600

## Screenshots of changes (if applicable)
**When there is a different first court hearing**
Screenshot 2023-10-03 at 15 31 27

**When first court hearing is the same as next court hearing**
Screenshot 2023-10-03 at 15 31 42

## How to manually test the feature
In localhost, you will need to also use the datastore in the branch above mentioned in order to render submitted applications.
For in progress applications, go to the next court hearing page, and select different options to the question "Did this court also hear the first hearing?" and fill the first court hearing if the answer is "No". Observe the CYA page will show/hide this accordingly.

### CODE REVIEW

**Review by mseedat-moj — APPROVED** [review]
lovely

**Comment by willmcb** [comment]
On the show page after submission it does not show the "Did this court also show the first court hearing" answer:
Screenshot 2023-10-03 at 17 51 02

To compare with CYA this is after submitting:

Screenshot 2023-10-03 at 17 50 37

**Review by willmcb — CHANGES_REQUESTED** [review]
Works well I just have a comment on the show page after submission - maybe we are doing this in a separate PR but would be good to know what your thinking is :)

**Comment by zheileman** [comment]
Added the serialisation, let me know. You can now use `main` branch in datastore as the PR in that repo has been merged 👍

**Review by willmcb — APPROVED** [review]
Brilliant

**Pull request merged**
