### PR TITLE
CRIMAPP-359 Update to govuk-frontend 5.0.0

### PR DESCRIPTION
**Pull request by RoseSAK**
## Description of change

This PR updates the govuk-frontend library to the most recent version - 5.0.0. It also updates MoJ frontend to 2.0.1 and the govuk-formbuilder gem to 5.0.0 (the most recent versions), to bring them in line with the changes made in govuk-frontend. The gov-components gem was also added. 

Other changes:
* Updated the phase banner to show a different colour and tag for each environment (prod, staging and local)
* Updated the header and navigation to use the components from govuk-components

Change tracker here, which shows all updates made for both breaking changes and non-breaking changes: https://docs.google.com/spreadsheets/d/1KdSpY6bFgI6lg7bMWrkze_4WcC_B08DB3kmUOPxuDlk/edit#gid=0 

All changes in govuk-frontend 5.0.0 are described here: https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0

## Link to relevant ticket

[CRIMAPP-359](https://dsdmoj.atlassian.net/browse/CRIMAPP-359 )

## How to manually test the feature

Regression test that everything renders properly and looks okay. Check that components using JS work as expected, e.g. the details component. Check that pagination works. [Tag styles ](https://design-system.service.gov.uk/components/tag/) have changed, but everything else should look the same as before. 

[CRIMAPP-359]: https://dsdmoj.atlassian.net/browse/CRIMAPP-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by willmcb** [comment]
I think the dev tag at the top is slightly wrong as it should have light orange colour text rather than black in orange
Screenshot 2024-01-26 at 09 47 30

Whereas on Review it is (granted its green but the gradient between the background and the text colour is correct):
Screenshot 2024-01-26 at 09 48 16

**Comment by arthurashman** [comment]
@willmcb @RoseSAK I'd be keen to keep Apply and Review Local banners consistent anyway - Is it possible to switch from orange local to green dev banner/tag?

**Comment by arthurashman** [comment]
The next/previous buttons on pagination look a little different to those on Review. Can we remove the heavy black outline on cick? 
image

**Comment by arthurashman** [comment]
This is Review for context 
image

**Comment by arthurashman** [comment]
Otherwise all looks great, thanks Rose! Regression tested and it looks as expected

**Review by arthurashman — APPROVED** [review]
Excellent work, thanks @RoseSAK - all looks great and as expected 👍

**Pull request merged**
